language: go

go:
- 1.8
- 1.9

cache:
  directories:
  - vendor

before_install:
- go get -u github.com/golang/dep/cmd/dep
- go get -u github.com/golang/lint/golint

install:
- dep ensure -v

script:
- make ci-test
- go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
